// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gunfwcluiygeywayypbd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd1bmZ3Y2x1aXlnZXl3YXl5cGJkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzMjE0MjMsImV4cCI6MjA3MTg5NzQyM30.6fZzCjC-VRH0aRKMZea38FDvj40Et50-QGYY6wDMi0g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});